### ISSUE TITLE
无法解析的外部符号SDL_main

### ISSUE THREAD

**Issue by Penguin-SAMA** [star-hengxing/software_renderer#1]
![image](https://github.com/star-hengxing/software_renderer/assets/50973632/f754c83d-8ad1-4770-96eb-4f40e9de5811)
你好，可以问问这个怎么解决吗

**Comment by star-hengxing** [comment]
上游包管理仓库引入的问题，再试试

```sh
git pull
xrepo update-repo
xmake f -c -y
xmake
```

**Comment by Penguin-SAMA** [comment]
![image](https://github.com/star-hengxing/software_renderer/assets/50973632/8b4ffa47-59b6-494a-8cd5-9e5fad12b12c)
奇怪，为啥要求的是v144工具集，现在最新的也才143啊(

**Comment by star-hengxing** [comment]
第一次见这种报错。。感觉是 cmake 对 vs preview 的支持可能不太完善。可以先试试清理全局缓存，然后看一下完整 log

```sh
xmake g -c
xmake f -c -y -vD
```

**Comment by Penguin-SAMA** [comment]
还真是preview的问题，我把preview退回到17.9就行了，谢谢大佬~

**Comment by star-hengxing** [comment]
> 奇怪，为啥要求的是v144工具集，现在最新的也才143啊(

xmake 对此做了 [workaround](https://github.com/xmake-io/xmake/pull/4800)，可以更新到 dev 来使用了
